### ISSUE TITLE
IBA filter not respected

### ISSUE THREAD

**Issue by steffilazerte** [BirdsCanada/naturecounts#21]
Hi @denislepage,

Are the naturecounts API filters still working as expected?

My tests show an issue with the IBA filter (at least). 
This query, is returning all records, not just for IBA AB001...

Entry point:  `/api/data/list_collections`
Query: `info=nc_test&token=XXXX&filter={"bmdeVersion":"BMDE2.00-min","iba":["IBA.AB001"]}`

**Comment by denislepage** [comment]
I just posted a fix in sandbox, @steffilazerte could you kindly test it? We recently made some changes that created this issue.

**Comment by denislepage** [comment]
Perfect. That is the expected behaviour. We'll deploy shortly to live.

**Comment by steffilazerte** [comment]
@denislepage, @cjardine-bsc are we going live with this soon?

**Comment by cjardine-bsc** [comment]
This should (I think) have already been pushed. Is it not working on live?

**Comment by steffilazerte** [comment]
You're right, awesome, I'll finish the release today 🎉
