### ISSUE TITLE
API list_collections erroring

### ISSUE THREAD

**Issue by steffilazerte** [BirdsCanada/naturecounts#24]
@denislepage @cjardine-bsc 

This API endpoint has been erroring for me: 
https://naturecounts.ca/api/data/list_collections

```
entryPoint	"/data/list_collections"
errorMsgs	
0	"An error has occurred"
1	'java.lang.NullPointerException: Cannot invoke "org.bsc.monitoring.Dataset.getAknLevel()" because "ds" is null'
error	500
msgCode	"unknown-error"
```

Has the API usage changed?

**Comment by denislepage** [comment]
Looking at the code, I think this can happen when new collections are added, but the cached lookup in Java isn’t yet refreshed. There was a check for this, but it only applied when the user authentication was also provided.

I just refreshed the lookup, if you want to try. I’ll post a fix as well. It’ll simply ignore new datasets until the lookup is refreshed.

**Comment by cjardine-bsc** [comment]
That checks out. I added a new collection (Mountain Bird Watch) last night.
